// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 17:46:50 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include "_cgo_export.h"
#include "cgo_helpers.h"

int dc_cancel_callback_t_a57c535d(void* userdata) {
	return cancelCallbackA57C535D(userdata);
}

void dc_event_callback_t_d245bf1c(dc_device_t* device, dc_event_type_t event, void* data, void* userdata) {
	eventCallbackD245BF1C(device, event, data, userdata);
}

int dc_dive_callback_t_1a75734a(unsigned char* data, unsigned int size, unsigned char* fingerprint, unsigned int fsize, void* userdata) {
	return diveCallback(data, size, fingerprint, fsize, userdata);
}

void dc_logfunc_t_38998c27(dc_context_t* context, dc_loglevel_t loglevel, char* file, unsigned int line, char* function, char* message, void* userdata) {
	logfunc38998C27(context, loglevel, file, line, function, message, userdata);
}

void dc_sample_callback_t_a3bf8997(dc_sample_type_t _type, dc_sample_value_t value, void* userdata) {
	sampleCallbackA3BF8997(_type, value, userdata);
}

