// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 01 Jun 2018 23:25:14 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include <stddef.h>
#include "libdivecomputer/parser.h"
#include "libdivecomputer/device.h"
#include "libdivecomputer/version.h"
#include "libdivecomputer/context.h"
#include "libdivecomputer/descriptor.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

// dc_sample_callback_t_a3bf8997 is a proxy for callback dc_sample_callback_t.
void dc_sample_callback_t_a3bf8997(dc_sample_type_t _type, dc_sample_value_t value, void* userdata);

// dc_logfunc_t_38998c27 is a proxy for callback dc_logfunc_t.
void dc_logfunc_t_38998c27(dc_context_t* context, dc_loglevel_t loglevel, char* file, unsigned int line, char* function, char* message, void* userdata);

// dc_cancel_callback_t_a57c535d is a proxy for callback dc_cancel_callback_t.
int dc_cancel_callback_t_a57c535d(void* userdata);

// dc_event_callback_t_d245bf1c is a proxy for callback dc_event_callback_t.
void dc_event_callback_t_d245bf1c(dc_device_t* device, dc_event_type_t event, void* data, void* userdata);

// dc_dive_callback_t_1a75734a is a proxy for callback dc_dive_callback_t.
int dc_dive_callback_t_1a75734a(unsigned char* data, unsigned int size, unsigned char* fingerprint, unsigned int fsize, void* userdata);

