// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 01 Jun 2018 23:25:14 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

package core

/*
#cgo pkg-config: libdivecomputer
#include <stddef.h>
#include "libdivecomputer/parser.h"
#include "libdivecomputer/device.h"
#include "libdivecomputer/version.h"
#include "libdivecomputer/context.h"
#include "libdivecomputer/descriptor.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// DcGasmixUnknown as defined in libdivecomputer/parser.h:145
	DcGasmixUnknown = 0xFFFFFFFF
	// DcTimezoneNone as defined in libdivecomputer/datetime.h:29
	DcTimezoneNone = 0x80000000
	// PkgVersion as defined in libdivecomputer/version.h:29
	PkgVersion = "0.6.0"
	// PkgVersionMajor as defined in libdivecomputer/version.h:30
	PkgVersionMajor = 0
	// PkgVersionMinor as defined in libdivecomputer/version.h:31
	PkgVersionMinor = 6
	// PkgVersionMicro as defined in libdivecomputer/version.h:32
	PkgVersionMicro = 0
)

// SampleType as declared in libdivecomputer/parser.h:50
type SampleType int32

// SampleType enumeration from libdivecomputer/parser.h:50
const (
	DcSampleTime        SampleType = iota
	DcSampleDepth       SampleType = 1
	DcSamplePressure    SampleType = 2
	DcSampleTemperature SampleType = 3
	DcSampleEvent       SampleType = 4
	DcSampleRbt         SampleType = 5
	DcSampleHeartbeat   SampleType = 6
	DcSampleBearing     SampleType = 7
	DcSampleVendor      SampleType = 8
	DcSampleSetpoint    SampleType = 9
	DcSamplePpo2        SampleType = 10
	DcSampleCns         SampleType = 11
	DcSampleDeco        SampleType = 12
	DcSampleGasmix      SampleType = 13
)

// FieldType as declared in libdivecomputer/parser.h:66
type FieldType int32

// FieldType enumeration from libdivecomputer/parser.h:66
const (
	DcFieldDivetime           FieldType = iota
	DcFieldMaxdepth           FieldType = 1
	DcFieldAvgdepth           FieldType = 2
	DcFieldGasmixCount        FieldType = 3
	DcFieldGasmix             FieldType = 4
	DcFieldSalinity           FieldType = 5
	DcFieldAtmospheric        FieldType = 6
	DcFieldTemperatureSurface FieldType = 7
	DcFieldTemperatureMinimum FieldType = 8
	DcFieldTemperatureMaximum FieldType = 9
	DcFieldTankCount          FieldType = 10
	DcFieldTank               FieldType = 11
	DcFieldDivemode           FieldType = 12
)

// Water as declared in libdivecomputer/parser.h:118
type Water int32

// Water enumeration from libdivecomputer/parser.h:118
const (
	DcWaterFresh Water = iota
	DcWaterSalt  Water = 1
)

// Divemode as declared in libdivecomputer/parser.h:125
type Divemode int32

// Divemode enumeration from libdivecomputer/parser.h:125
const (
	DcDivemodeFreedive Divemode = iota
	DcDivemodeGauge    Divemode = 1
	DcDivemodeOc       Divemode = 2
	DcDivemodeCc       Divemode = 3
)

// DecoType as declared in libdivecomputer/parser.h:132
type DecoType int32

// DecoType enumeration from libdivecomputer/parser.h:132
const (
	DcDecoNdl        DecoType = iota
	DcDecoSafetystop DecoType = 1
	DcDecoDecostop   DecoType = 2
	DcDecoDeepstop   DecoType = 3
)

// Tankvolume as declared in libdivecomputer/parser.h:151
type Tankvolume int32

// Tankvolume enumeration from libdivecomputer/parser.h:151
const (
	DcTankvolumeNone     Tankvolume = iota
	DcTankvolumeMetric   Tankvolume = 1
	DcTankvolumeImperial Tankvolume = 2
)

// Status as declared in libdivecomputer/common.h:42
type Status int32

// Status enumeration from libdivecomputer/common.h:42
const (
	DcStatusSuccess     Status = iota
	DcStatusDone        Status = 1
	DcStatusUnsupported Status = -1
	DcStatusInvalidargs Status = -2
	DcStatusNomemory    Status = -3
	DcStatusNodevice    Status = -4
	DcStatusNoaccess    Status = -5
	DcStatusIo          Status = -6
	DcStatusTimeout     Status = -7
	DcStatusProtocol    Status = -8
	DcStatusDataformat  Status = -9
	DcStatusCancelled   Status = -10
)

// Family as declared in libdivecomputer/common.h:94
type Family int32

// Family enumeration from libdivecomputer/common.h:94
const (
	DcFamilyNull               Family = iota
	DcFamilySuuntoSolution     Family = (1 << 16)
	DcFamilySuuntoEon          Family = 65537
	DcFamilySuuntoVyper        Family = 65538
	DcFamilySuuntoVyper2       Family = 65539
	DcFamilySuuntoD9           Family = 65540
	DcFamilySuuntoEonsteel     Family = 65541
	DcFamilyReefnetSensus      Family = (2 << 16)
	DcFamilyReefnetSensuspro   Family = 131073
	DcFamilyReefnetSensusultra Family = 131074
	DcFamilyUwatecAladin       Family = (3 << 16)
	DcFamilyUwatecMemomouse    Family = 196609
	DcFamilyUwatecSmart        Family = 196610
	DcFamilyUwatecMeridian     Family = 196611
	DcFamilyUwatecG2           Family = 196612
	DcFamilyOceanicVtpro       Family = (4 << 16)
	DcFamilyOceanicVeo250      Family = 262145
	DcFamilyOceanicAtom2       Family = 262146
	DcFamilyMaresNemo          Family = (5 << 16)
	DcFamilyMaresPuck          Family = 327681
	DcFamilyMaresDarwin        Family = 327682
	DcFamilyMaresIconhd        Family = 327683
	DcFamilyHwOstc             Family = (6 << 16)
	DcFamilyHwFrog             Family = 393217
	DcFamilyHwOstc3            Family = 393218
	DcFamilyCressiEdy          Family = (7 << 16)
	DcFamilyCressiLeonardo     Family = 458753
	DcFamilyZeagleN2ition3     Family = (8 << 16)
	DcFamilyAtomicsCobalt      Family = (9 << 16)
	DcFamilyShearwaterPredator Family = (10 << 16)
	DcFamilyShearwaterPetrel   Family = 655361
	DcFamilyDiveriteNitekq     Family = (11 << 16)
	DcFamilyCitizenAqualand    Family = (12 << 16)
	DcFamilyDivesystemIdive    Family = (13 << 16)
	DcFamilyCochranCommander   Family = (14 << 16)
)

// Loglevel as declared in libdivecomputer/context.h:40
type Loglevel int32

// Loglevel enumeration from libdivecomputer/context.h:40
const (
	DcLoglevelNone    Loglevel = iota
	DcLoglevelError   Loglevel = 1
	DcLoglevelWarning Loglevel = 2
	DcLoglevelInfo    Loglevel = 3
	DcLoglevelDebug   Loglevel = 4
	DcLoglevelAll     Loglevel = 5
)

// Transport as declared in libdivecomputer/descriptor.h:39
type Transport int32

// Transport enumeration from libdivecomputer/descriptor.h:39
const (
	DcTransportNone      Transport = iota
	DcTransportSerial    Transport = 1
	DcTransportUsb       Transport = 2
	DcTransportUsbhid    Transport = 3
	DcTransportIrda      Transport = 4
	DcTransportBluetooth Transport = 5
)

// EventType as declared in libdivecomputer/device.h:41
type EventType int32

// EventType enumeration from libdivecomputer/device.h:41
const (
	DcEventWaiting  EventType = (1 << 0)
	DcEventProgress EventType = (1 << 1)
	DcEventDevinfo  EventType = (1 << 2)
	DcEventClock    EventType = (1 << 3)
	DcEventVendor   EventType = (1 << 4)
)
