// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 01 Jun 2018 23:25:14 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package libdivecomputer-go provides Go bindings for libdivecomputer, by Jef Driesen
*/
package core
