// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 05 Jun 2018 17:46:50 CEST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package libdivecomputer-go provides Go bindings for libdivecomputer, by Jef Driesen
*/
package core
